using Meteion.Toolkit.Localization.Abstractions;
using System.ComponentModel;
using System.Reflection;

namespace Meteion.Toolkit.WPF.Localization.Extensions;

/// <summary>
/// Powers the "Key=..." attribute-value dropdown for <see cref="LocalizedValueExtension.Key"/>
/// in Visual Studio's XAML editor, by listing every resource key found on a class generated by
/// <c>Meteion.Toolkit.Localization.KeysGenerator</c> - anywhere in the currently loaded
/// assemblies, not just the consuming project's own.
/// </summary>
/// <remarks>
/// Not exclusive (<see cref="GetStandardValuesExclusive"/> returns <see langword="false"/>):
/// this is a convenience list, not a validator, since a key can also come from
/// <see cref="LocalizedValueExtension.KeyBinding"/> at runtime, from a resx this converter
/// can't see (e.g. a different, not-yet-loaded assembly), or from before the generator has run
/// on a brand-new key. Discovery happens via reflection over loaded assemblies rather than a
/// compile-time reference, since the generated keys class lives in the *consuming*
/// project/assembly, not this one.
/// </remarks>
public class LocalizationKeyConverter : StringConverter
{
    // Cheap invalidation: re-scan only when the set of loaded assemblies has actually
    // changed since the last call, rather than reflecting over everything on every keystroke
    // in the XAML editor.
    private static int _cachedAssemblyCount = -1;
    private static string[] _cachedKeys = [];

    public override bool GetStandardValuesSupported(ITypeDescriptorContext? context) => true;

    // Not exclusive - see remarks above.
    public override bool GetStandardValuesExclusive(ITypeDescriptorContext? context) => false;

    public override StandardValuesCollection GetStandardValues(ITypeDescriptorContext? context) =>
        new(DiscoverKeys());

    private static string[] DiscoverKeys()
    {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        if (assemblies.Length == _cachedAssemblyCount)
        {
            return _cachedKeys;
        }

        var keys = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var assembly in assemblies)
        {
            Type[] types;
            try
            {
                types = assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                types = ex.Types.Where(t => t is not null).ToArray()!;
            }
            catch (Exception)
            {
                // Dynamic/reflection-only assemblies, or anything else that can't be
                // enumerated at design time - just skip it, this is a best-effort list.
                continue;
            }

            foreach (var type in types)
            {
                if (!type.IsDefined(typeof(GeneratedLocalizationKeysAttribute), inherit: false))
                {
                    continue;
                }

                foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
                {
                    if (field.FieldType == typeof(string) && field.IsLiteral &&
                        field.GetRawConstantValue() is string value)
                    {
                        keys.Add(value);
                    }
                }
            }
        }

        _cachedAssemblyCount = assemblies.Length;
        _cachedKeys = [.. keys];
        return _cachedKeys;
    }
}
