namespace Meteion.Toolkit.Localization.Abstractions;

/// <summary>
/// Marks a class as generated by <c>Meteion.Toolkit.Localization.KeysGenerator</c> from a
/// neutral .resx localization resource - a set of <c>public const string</c> fields whose
/// name mirrors the resx key and whose value is the qualified key (see <see cref="LocalizationKey"/>;
/// the field's own XML doc comment has the resx entry's neutral-culture value), plus a
/// <c>ResxSource</c> constant identifying the resx itself.
/// </summary>
/// <remarks>
/// Consumers generally don't need to reference this attribute directly - it exists so
/// design-time tooling (e.g. <c>LocalizationKeyConverter</c> in
/// <c>Meteion.Toolkit.WPF.Localization</c>) can find every generated keys class across all
/// loaded assemblies via reflection, without needing a compile-time reference to any one of
/// them, to power <c>Key="..."</c> IntelliSense in the XAML editor.
/// </remarks>
[AttributeUsage(AttributeTargets.Class)]
public sealed class GeneratedLocalizationKeysAttribute : Attribute
{
    /// <summary>
    /// The path of the source .resx file, as recorded by the generator. Relative to the
    /// project that produced this class, but not guaranteed to exist on disk at consumption
    /// time (e.g. when this class is used from a different project than the one that built it) -
    /// informational only.
    /// </summary>
    public string? ResxPath { get; }

    /// <summary>
    /// The resx identity (<c>&lt;AssemblyName&gt;/&lt;ResourceBaseName&gt;</c>) this class's keys
    /// belong to - the same value as the class's generated <c>ResxSource</c> constant.
    /// </summary>
    public string? ResxSource { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="GeneratedLocalizationKeysAttribute"/> class without a resx path.
    /// </summary>
    public GeneratedLocalizationKeysAttribute() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="GeneratedLocalizationKeysAttribute"/> class.
    /// </summary>
    /// <param name="resxPath">The path of the source .resx file, as recorded by the generator.</param>
    public GeneratedLocalizationKeysAttribute(string resxPath) => ResxPath = resxPath;
}
